{
  products {
    _id
    title
    imagesURL
    images
    price
    count
    discount
    category {
      _id
      title
    }
    tags
    supplier {
      _id
      first_name
      last_name
    }
    features {
      length
      weight
      width
      height
    }
  }
}
